### ISSUE TITLE
Error 500 when I try to delete an task

### ISSUE THREAD

**Issue by Messhias** [drigon/drigon-todo-list#1]
- Login 
- Create more than 3 tasks.
- Select all the tasks in the checkbox.
- Click on `x` to exclude.

See the screenshot bellow:

<img width="1440" alt="Screenshot 2021-12-21 at 20 05 04" src="https://user-images.githubusercontent.com/1161283/146991080-fc5faeeb-c03e-4653-a534-cbee507dc69b.png">

**Comment by drigon** [comment]
Fixed, the issue was when clicking too fast, the element hadn't yet been removed from the page, add at condition to check
